version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "127.0.0.1:5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - app_network
    ports:
      - "127.0.0.1:6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_NAME}
    networks:
      - app_network
    volumes:
      - bot_logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
  backup:
    image: postgres:15-alpine
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./scripts/backup:/scripts
      - db_backups:/app/data/backups
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_NAME=${POSTGRES_NAME}
    networks:
      - app_network
    entrypoint: ["sh", "-c"]
    command: |
      "
      apk add --no-cache bash findutils
      chmod +x /scripts/postgres-backup.sh
      chmod +x /scripts/postgres-restore.sh
      echo '0 2 * * * /scripts/postgres-backup.sh >> /app/data/backups/backup.log 2>&1' > /var/spool/cron/crontabs/root
      crond -f -d 8
      "

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  bot_logs:
  db_backups: 