services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "127.0.0.1:5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - app_network
    ports:
      - "127.0.0.1:6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_NAME}
      - NODE_ENV=production
      - WEBHOOK_PORT=3000
    networks:
      - app_network
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - bot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/web/html:/app/data/web/html
    networks:
      - app_network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    
  backup:
    image: postgres:15-alpine
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./scripts/backup:/scripts
      - db_backups:/app/data/backups
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_NAME=${POSTGRES_NAME}
    networks:
      - app_network
    entrypoint: ["sh", "-c"]
    command: |
      "
      apk add --no-cache bash findutils
      chmod +x /scripts/postgres-backup.sh
      chmod +x /scripts/postgres-restore.sh
      echo '0 2 * * * /scripts/postgres-backup.sh >> /app/data/backups/backup.log 2>&1' > /var/spool/cron/crontabs/root
      crond -f -d 8
      "
  
  log-viewer:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:3030:3030"  # Доступен только локально, проксируется через nginx
    environment:
      - LOG_VIEWER_PORT=3030
    volumes:
      - ./logs:/app/logs
      - ./scripts:/app/scripts
    command: node scripts/log-viewer/log-server.js
    networks:
      - app_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 

  # Prisma Studio - веб-интерфейс для управления базой данных
  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: npx prisma studio --port 5555 --hostname 0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    ports:
      - "127.0.0.1:5555:5555"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_NAME}
      - BROWSER=none # Отключаем автоматическое открытие браузера
    volumes:
      - ./prisma:/app/prisma

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  db_backups: 